### ISSUE TITLE
[BUG]: Dynamic directive fails to trap keyboard at first

### ISSUE THREAD

**Issue by J-Sek** [pdanpdan/vue-keyboard-trap#6]
**Describe the bug**
I tried to use dynamic directive, but it works partially. First round of tabbing escapes the trap. When I go back inside (e.g. using `[SHIFT]` + `[TAB]`), the trap works.

```html
<dialog v-kbd-trap='visible'>
  <!-- content -->
</dialog>
```

[Example on CodeSandbox](https://codesandbox.io/p/sandbox/vue-keyboard-trap-issue-ctw8z7)

**To Reproduce**
1. Use `v-kbd-trap="enabled"` on a rendered element
2. Open a dialog (should change `enabled` to `true`)
3. Click `[TAB]` few times
    - This will focus elements outside of the dialog
4. Click `[SHIFT]` + `[TAB]` to get back into the dialog
5. Click `[TAB]` few times again
    - This will keep focus inside the dialog

**Expected behavior**
The directive should keep focus inside all the time

**Recording**
![Peek 2023-09-26 13-38](https://github.com/pdanpdan/vue-keyboard-trap/assets/20162853/fbcb9593-b8cb-4756-878d-e68909382bd4)

**Environment:**
 - OS: Ubuntu 20.04
 - Browser: Chrome, Edge, Firefox (latest versions)

**Workaround**
Additional `<div>` with `v-if`... so actually it means you cannot use "dynamic" mode at all.

```html
<dialog>
  <div v-if='visible' v-kbd-trap>
    <!-- content -->
  <div>
</dialog>
```

**Comment by pdanpdan** [comment]
Thank you for reporting. Should be fixed with v1.0.18 on npm

**Comment by J-Sek** [comment]
Thanks. I can see the newest version prevents focus outside of dialog, but the outline is missing on links for some reason. It also disappears when I click on one of the links... looks more like a browser issue.

![Peek 2023-09-27 14-48](https://github.com/pdanpdan/vue-keyboard-trap/assets/20162853/cc574446-03bc-45a9-b47d-0bd0376969f1)

However I can mitigate it by using `:inert="!visible"` next to the `v-kdb-trap='visible'`.

```html
<dialog ref="dialog" :inert="!visible" v-kbd-trap="visible">
  <!-- content -->
</dialog>
```

**Comment by pdanpdan** [comment]
Same codesandbox url?

**Comment by J-Sek** [comment]
After reading [spec](https://www.w3.org/TR/selectors-4/#the-focus-visible-pseudo) I suspect that Chrome is more in-line with the requirements:

> If the previously-focused element indicated focus, and a script causes focus to move elsewhere, the newly focused element should indicate focus.

> Conversely, if the previously-focused element did not indicate focus, and **a script causes focus to move** elsewhere, the newly focused element **should also not indicate focus**.

- Mousedown focuses button with regular `:focus` and opens dialog (programatically)
- When opened `:focus` shifts now to the first link on the list
- Tabbing continues to keep `:focus` because it is actually intercepted by `v-kdb-trap` so every next selection is considered to be done via "a script"

The button and inputs behave different than links... maybe because of heuristics mentioned by the spec.

Your helper function calling `.focus()` could make use of `focusVisible` option once stops being experimental. [Current coverage](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus#browser_compatibility) is quite poor.

Overall I can live with 2 workarounds (`inert` and additional `<div v-if>`). No need to stress about it. Thanks to your timely responses I digged more and learned something new 😄 And the focus is trapped inside the dialog, so the issue was successfully resolved.

**Comment by pdanpdan** [comment]
I would agree with them if they were consistent.
But if the link has no style for `focus-visible` and no `tabindex` then the outline is not shown, while any of the 2 is present the indicator is shown.

**Comment by J-Sek** [comment]
I think you mean `a:focus` has no outline, hence is not visible in the example. `a:focus-visible` does not require any styles as it gets 1px outline from the built-in browser stylesheet.

**Comment by J-Sek** [comment]
Oh... I see. The styles for `:focus-visible` for `<a>` tell Chrome's heuristics to add `focus-visible` state in situations when it would normally only use only `focus`.

The generic CSS rule should be a decent way to force some consistency across the browsers, for now.

**Comment by pdanpdan** [comment]
You should upgrade to v1.0.19 - a fix not to add `tabindex` to `dialog` 
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#attributes
